### ISSUE TITLE
ImportError: cannot import name 'core' from 'backend.core' 

### ISSUE THREAD

**Issue by gigatux2008** [Adapt-Development/J.A.R.V.I.S#4]
this error just appeared after I run this program and the text editor I was using was visual studio code.

**Comment by SaptakBhoumik** [comment]
In visual Studio click on file then click on open folder. Then run it

**Comment by gigatux2008** [comment]
I WAS TALKING ABOUT WHOLE PROGRAM

**Comment by SaptakBhoumik** [comment]
What do you want to say

**Comment by gigatux2008** [comment]
When i run the app.py then this is the problem

**Comment by SaptakBhoumik** [comment]
You have to open it as a folder in vs code

**Comment by gigatux2008** [comment]
okay i try that also

**Comment by SaptakBhoumik** [comment]
Let me know if it works

**Comment by gigatux2008** [comment]
it is showing a screen of a size of mobile with it is showing error file not found

**Comment by SaptakBhoumik** [comment]
Did you delete the templates folder? @gigatux2008

**Comment by gigatux2008** [comment]
no not at all

**Comment by SaptakBhoumik** [comment]
Ok go to line 48 of app.py and change the url to  https://adapt-development.github.io/J.A.R.V.I.S/templates/

**Comment by SaptakBhoumik** [comment]
Some people face this @gigatux2008

**Comment by gigatux2008** [comment]
one minute i just changed the name of the file index.html to check if it will work then now i am running again

**Comment by gigatux2008** [comment]
after that line 48 correction also it is showing white screen

**Comment by SaptakBhoumik** [comment]
@gigatux2008 let me know after it works

**Comment by gigatux2008** [comment]
after that line 48 correction also it is showing white screen

**Comment by gigatux2008** [comment]
with outlines of a mobile

**Comment by SaptakBhoumik** [comment]
Can you share a screenshot

**Comment by gigatux2008** [comment]
![image](https://user-images.githubusercontent.com/86052863/122384842-b6d7d780-cf89-11eb-8167-98bb87b23b9b.png)

**Comment by SaptakBhoumik** [comment]
@gigatux2008 do you have a stable internet connection

**Comment by gigatux2008** [comment]
yes it is what should be ideal speed for running this

**Comment by SaptakBhoumik** [comment]
Can you contact me on discord

**Comment by gigatux2008** [comment]
yes sure

**Comment by SaptakBhoumik** [comment]
@gigatux2008 Saptak#7383 my id

**Comment by SaptakBhoumik** [comment]
Solved
